### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by alina-thorzen** [annaet/cypress-tags#118]
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`C:\Work\cypress-project\cypress\plugins\index.js`)

 TypeError: Cannot read property 'createOmittedExpression' of undefined
    at visit (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:178:47)
    at C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:84
    at visitNode (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74798:23)
    at Object.visitEachChild (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:75133:59)
    at visit (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:47)
    at C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:84
    at visitNodes (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74849:48)
    at Object.visitEachChild (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:75129:45)
    at visit (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:47)
    at C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:84
    at visitNode (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74798:23)
    at visitFunctionBody (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74954:23)
    at Object.visitEachChild (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:75091:363)
    at visit (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:47)
    at C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:84
    at visitNodes (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74849:48)
    at Object.visitEachChild (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:75079:156)
    at visit (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:47)
    at C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:84
    at visitNode (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74798:23)
    at Object.visitEachChild (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:75133:59)
    at visit (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:47)
    at C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:84
    at visitNodes (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74849:48)
    at visitLexicalEnvironment (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74882:22)
    at Object.visitEachChild (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:75249:54)
    at visit (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:181:47)
    at Object.visitNode (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:74798:23)
    at C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:185:33
    at transformation (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:94097:24)
    at Object.map (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:551:29)
    at Object.transformNodes (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:94104:30)
    at Object.transform (C:\Work\cypress-project\node_modules\typescript\lib\typescript.js:140789:25)
    at processFile (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:190:52)
    at Stream.onend (C:\Work\cypress-project\node_modules\cypress-tags\dist\index.js:201:20)
    at _end (C:\Work\cypress-project\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Work\cypress-project\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\Work\cypress-project\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:421:28)
    at DestroyableTransform.emit (events.js:327:22)
    at endReadableNT (C:\Work\cypress-project\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Warning: We failed processing this video.

This error will not alter the exit code.

**Comment by annaet** [comment]
Hi @alina-thorzen 

Can you provide some more information on your environment please to help debug this issue? What version of typescript are you using?

Are you able to run the [example project](https://github.com/annaet/cypress-tags-example) successfully?

**Comment by jinisha** [comment]
I am using typescript 3.8.3 version and getting the same issue.

**Comment by jinisha** [comment]
@annaet I was able to run your working example successfully after I modified the package.json scripts a bit.

![image](https://user-images.githubusercontent.com/9576963/140822855-a32ae242-5c54-41b2-9bf7-0a3d6a51744f.png)

**Comment by annaet** [comment]
@jinisha 

The cypress-tags projects are using typescript v4.3.5 so it may be worth updating to ensure it runs smoothly.

Please see my comment on your other issue regarding environment variables.
