### ISSUE TITLE
Plugin crashes when running cypress (windows 10, cypress 5.6.0)

### ISSUE THREAD

**Issue by PetMou** [annaet/cypress-tags#13]
Plugin crashes when running cypress (windows 10, cypress 5.6.0):

```
C:\Projecten\dwd>cypress run --headless --browser chrome --config-file cypress/configs/dev.json --env CYPRESS_INCLUDE_TAGS=auth


================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    5.6.0                                                                              │
  │ Browser:    Chrome 88 (headless)                                                               │
  │ Specs:      32 found (01authorisatie_A\01inloggen.spec.js, 02zaak_A\01zaken-tab.spec.js, 02zaa │
  │             k_A\02zaak-partijnamen.spec.js, 02zaak_A\03printen-voorhouden.spec.js, 03stapels_A │
  │             \01losse-stapel.spec.js, 03stapels_A\02enkele-stapel.spec.js, 03stapels_A\03meerde │
  │             re-stapels....)                                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  01authorisatie_A\01inloggen.spec.js                                            (1 of 32)

The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`C:\Projecten\dwd\cypress\plugins\index.js`)

 TypeError: Cannot read property 'createNodeArray' of undefined
    at removeTagsFromNode (C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:92:42)
    at visit (C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:116:40)
    at C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:154:84
    at visitNode (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:74775:23)
    at Object.visitEachChild (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:75110:59)
    at visit (C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:154:47)
    at C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:154:84
    at visitNodes (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:74826:48)
    at visitLexicalEnvironment (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:74859:22)
    at Object.visitEachChild (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:75226:54)
    at visit (C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:154:47)
    at Object.visitNode (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:74775:23)
    at C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:158:33
    at transformation (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:94068:24)
    at Object.map (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:551:29)
    at Object.transformNodes (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:94075:30)
    at Object.transform (C:\Projecten\dwd\node_modules\typescript\lib\typescript.js:140760:25)
    at processFile (C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:163:52)
    at Stream.onend (C:\Projecten\dwd\node_modules\cypress-tags\dist\index.js:174:20)
    at _end (C:\Projecten\dwd\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\Projecten\dwd\node_modules\through\index.js:74:5)
    at DestroyableTransform.onend (C:\Projecten\dwd\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:416:28)
    at DestroyableTransform.emit (events.js:322:22)
    at endReadableNT (C:\Projecten\dwd\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

Are there any dependencies I am missing?
In my situation I find 2 issues cypress couldn't cope with (from index.js):
```
    const newArgs = typescript_1.factory.createNodeArray([...node.arguments.slice(1)]);
    const newExpression = typescript_1.factory.createCallExpression(node.expression, undefined, newArgs);
```
When I remove all occurrences of 'factory' in the js and replace 'createCallExpression' with 'createCall' everything runs fine...

**Comment by annaet** [comment]
Hi @PetMou.

It looks like you're trying to use this in a JS file (`01authorisatie_A\01inloggen.spec.js`). Can you confirm if you're using TypeScript for this project?

Unfortunately this is a TypeScript only plugin, as it relies on traversing the TypeScript AST to find the tags and filter the tests.

**Comment by midleman** [comment]
> Hi @PetMou.
> 
> It looks like you're trying to use this in a JS file (`01authorisatie_A\01inloggen.spec.js`). Can you confirm if you're using TypeScript for this project?
> 
> Unfortunately this is a TypeScript only plugin, as it relies on traversing the TypeScript AST to find the tags and filter the tests.

At bare minimum, which files need to be converted to TS to be able to utilize this plugin?

**Comment by annaet** [comment]
I've just tested this out with a fresh project, and the plugin should work so long as typescript is installed as a dependency. You will not need to change any files to .ts files.

My test project used only the following dependencies and was able to utilise the plugin:

```
    "cypress": "^6.5.0",
    "cypress-tags": "0.0.20",
    "typescript": "^4.2.2"
```

@PetMou it sounds like you must have typescript installed somewhere if it's able to run the plugin at all, it's possible you're using a different version that maybe doesn't support the `createCallExpression`? Would you be able to double check that?

**Comment by PetMou** [comment]
Thanks! Upgrading the typescript version did the trick. I like this plugin very much!
