### ISSUE TITLE
Support cypress 6.0.0

### ISSUE THREAD

**Issue by efreethy** [annaet/cypress-tags#7]
### Repro
* upgrade cypress in package.json to `6.0.0`
* `npm run build`
* `npm t`

### Error
```
  8) Enum tags
       Exclude tags provided
         "before all" hook for "should output all tests without tags":
     Uncaught Error: Debug Failure. False expression: Unexpected node.
Verbose Debug Information: Node EmptyStatement did not pass test 'isExpression'.
      at visitNode (node_modules/typescript/lib/typescript.js:78336:18)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78682:64)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNodes (node_modules/typescript/lib/typescript.js:78375:48)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78678:50)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNode (node_modules/typescript/lib/typescript.js:78322:23)
      at visitFunctionBody (node_modules/typescript/lib/typescript.js:78493:23)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78637:372)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNodes (node_modules/typescript/lib/typescript.js:78375:48)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78625:173)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNode (node_modules/typescript/lib/typescript.js:78322:23)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78682:64)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNodes (node_modules/typescript/lib/typescript.js:78375:48)
      at visitLexicalEnvironment (node_modules/typescript/lib/typescript.js:78415:22)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78798:55)
      at visit (dist/index.js:154:47)
      at Object.visitNode (node_modules/typescript/lib/typescript.js:78322:23)
      at /Users/evanfreethy/Projects/personal/cypress-tags/dist/index.js:158:33
      at transformation (node_modules/typescript/lib/typescript.js:96806:24)
      at Object.map (node_modules/typescript/lib/typescript.js:643:29)
      at Object.transformNodes (node_modules/typescript/lib/typescript.js:96813:30)
      at Object.transform (node_modules/typescript/lib/typescript.js:145706:25)
      at processFile (dist/index.js:163:52)
      at Stream.onend (dist/index.js:174:20)
      at _end (node_modules/through/index.js:65:9)
      at Stream.stream.end (node_modules/through/index.js:74:5)
      at DestroyableTransform.onend (node_modules/readable-stream/lib/_stream_readable.js:577:10)
      at endReadableNT (node_modules/readable-stream/lib/_stream_readable.js:1010:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

  9) Enum tags
       Include and exclude tags provided
         "before all" hook for "should output all tests without tags":
     Uncaught Error: Debug Failure. False expression: Unexpected node.
Verbose Debug Information: Node EmptyStatement did not pass test 'isExpression'.
      at visitNode (node_modules/typescript/lib/typescript.js:78336:18)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78682:64)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNodes (node_modules/typescript/lib/typescript.js:78375:48)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78678:50)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNode (node_modules/typescript/lib/typescript.js:78322:23)
      at visitFunctionBody (node_modules/typescript/lib/typescript.js:78493:23)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78637:372)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNodes (node_modules/typescript/lib/typescript.js:78375:48)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78625:173)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNode (node_modules/typescript/lib/typescript.js:78322:23)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78682:64)
      at visit (dist/index.js:154:47)
      at typescript_1.default.visitEachChild (dist/index.js:154:84)
      at visitNodes (node_modules/typescript/lib/typescript.js:78375:48)
      at visitLexicalEnvironment (node_modules/typescript/lib/typescript.js:78415:22)
      at Object.visitEachChild (node_modules/typescript/lib/typescript.js:78798:55)
      at visit (dist/index.js:154:47)
      at Object.visitNode (node_modules/typescript/lib/typescript.js:78322:23)
      at /Users/evanfreethy/Projects/personal/cypress-tags/dist/index.js:158:33
      at transformation (node_modules/typescript/lib/typescript.js:96806:24)
      at Object.map (node_modules/typescript/lib/typescript.js:643:29)
      at Object.transformNodes (node_modules/typescript/lib/typescript.js:96813:30)
      at Object.transform (node_modules/typescript/lib/typescript.js:145706:25)
      at processFile (dist/index.js:163:52)
      at Stream.onend (dist/index.js:174:20)
      at _end (node_modules/through/index.js:65:9)
      at Stream.stream.end (node_modules/through/index.js:74:5)
      at DestroyableTransform.onend (node_modules/readable-stream/lib/_stream_readable.js:577:10)
      at endReadableNT (node_modules/readable-stream/lib/_stream_readable.js:1010:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)



npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! cypress-tags@0.0.16 mocha:run: `mocha -r ts-node/register --spec test/*.ts`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the cypress-tags@0.0.16 mocha:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/evanfreethy/.npm/_logs/2020-12-01T21_20_53_942Z-debug.log```

**Comment by bluepioupiou** [comment]
I will add that trying to add this plugin to a newly created cypress 6.0.0 env I've got this error

` TypeError: Cannot read property 'createEmptyStatement' of undefined`

will be nice to have these features on the last cypress version

**Comment by efreethy** [comment]
@annaet do you see this as a quick fix? I can take a stab at it if you are strapped. Would love to see cypress 6 support.

**Comment by annaet** [comment]
Sorry for the delay on replying to this - turns out I didn't have notifications set up for new issues!

I've upgraded the plugin to `cypress 6.1.0` and done used the new version in the [cypress-tags-example](https://github.com/annaet/cypress-tags-example) project.

Upgrading `cypress-tags` to `v0.0.17` should work for new projects now. Please let me know if you encounter any more issues with this!
