### ISSUE TITLE
Pluing Crashing

### ISSUE THREAD

**Issue by joxgarcia1997** [annaet/cypress-tags#77]
Today I clone the cypress-tags-example repository , I install the dependencies and try to run the cy:wip command but I have this happens

```
Joses-MacBook-Pro:cypress-tags-example josepablogarciapalacios$ npm run cy:wip

cypress-tags-example@0.0.1 cy:wip /Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example
CYPRESS_INCLUDE_TAGS=wip cypress run


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    7.4.0                                                                              │
  │ Browser:    Electron 89 (headless)                                                             │
  │ Specs:      1 found (enum.spec.ts)                                                             │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  enum.spec.ts                                                                    (1 of 1)

The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file (`/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/cypress/plugins/index.js`)

 Error: Debug Failure. Unhandled SyntaxKind: EmptyStatement.
    at pipelineEmitWithHintWorker (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104814:22)
    at pipelineEmitWithHint (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104364:17)
    at pipelineEmitWithComments (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107818:13)
    at pipelineEmit (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104304:13)
    at emitExpression (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104288:13)
    at emitExpressionStatement (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:105712:13)
    at pipelineEmitWithHintWorker (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104499:32)
    at pipelineEmitWithHint (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104364:17)
    at pipelineEmitWithComments (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107818:13)
    at pipelineEmit (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104304:13)
    at emit (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104277:13)
    at emitNodeList (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107065:25)
    at emitList (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:106952:13)
    at emitBlockFunctionBodyWorker (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:106016:17)
    at emitBodyWithDetachedComments (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107934:17)
    at emitBlockFunctionBody (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:105993:17)
    at emitSignatureAndBody (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:105932:21)
    at emitArrowFunction (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:105474:13)
    at pipelineEmitWithHintWorker (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104751:32)
    at pipelineEmitWithHint (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104364:17)
    at pipelineEmitWithComments (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107818:13)
    at pipelineEmit (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104304:13)
    at emitExpression (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104288:13)
    at emitNodeList (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107065:25)
    at emitExpressionList (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:106955:13)
    at emitCallExpression (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:105438:13)
    at pipelineEmitWithHintWorker (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104739:32)
    at pipelineEmitWithHint (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104364:17)
    at pipelineEmitWithComments (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107818:13)
    at pipelineEmit (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104304:13)
    at emitExpression (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104288:13)
    at emitExpressionStatement (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:105712:13)
    at pipelineEmitWithHintWorker (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104499:32)
    at pipelineEmitWithHint (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104364:17)
    at pipelineEmitWithComments (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107818:13)
    at pipelineEmit (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104304:13)
    at emit (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104277:13)
    at emitNodeList (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107065:25)
    at emitList (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:106952:13)
    at emitSourceFileWorker (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:106683:13)
    at emitBodyWithDetachedComments (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:107934:17)
    at emitSourceFile (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:106604:21)
    at pipelineEmitWithHintWorker (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104372:24)
    at pipelineEmitWithHint (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104364:17)
    at pipelineEmit (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104304:13)
    at print (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104240:13)
    at writeFile (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104224:13)
    at Object.printFile (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/typescript/lib/typescript.js:104085:13)
    at processFile (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/cypress-tags/dist/index.js:192:28)
    at Stream.onend (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/cypress-tags/dist/index.js:201:20)
    at _end (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:421:28)
    at DestroyableTransform.emit (events.js:327:22)
    at endReadableNT (/Users/josepablogarciapalacios/Documents/myProjects/cypress-tags-example/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Warning: We failed processing this video.

This error will not alter the exit code.

TimeoutError: operation timed out
    at afterTimeout (/Users/josepablogarciapalacios/Library/Caches/Cypress/7.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/Users/josepablogarciapalacios/Library/Caches/Cypress/7.4.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     enum.spec.ts                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  enum.spec.ts                               0ms        -        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                       0ms        -        -        1        -        -  

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress-tags-example@0.0.1 cy:wip: `CYPRESS_INCLUDE_TAGS=wip cypress run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress-tags-example@0.0.1 cy:wip script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/josepablogarciapalacios/.npm/_logs/2021-07-08T18_21_23_430Z-debug.log
```

Also, when I install the new cypress-tags module, I have this failures:

```
npm install cypress-tags
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
+ cypress-tags@0.1.0
updated 1 package and audited 606 packages in 16.091s

16 packages are looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

Im using a linux machine.

**Comment by annaet** [comment]
Hi,

This is a duplicate of https://github.com/annaet/cypress-tags/issues/58

I'm hoping to have a fix out later today so I'll close this one for now!
